[
  {
    "Event_ID": 0,
    "Concert/FM Title": "Like Seventeen – Boys Wish",
    "Start Date": "December 24, 2015",
    "City": "Seoul",
    "End Date": "December 26, 2015",
    "City__1": "Seoul",
    "Concert Poster": "all in folder",
    "Video": "https://www.youtube.com/watch?v=kRoR8xKQzds",
    "Note": ""
  },
  {
    "Event_ID": 1,
    "Concert/FM Title": "Like Seventeen – Boys Wish Encore Concert",
    "Start Date": "February 13, 2016",
    "City": "Seoul",
    "End Date": "February 14, 2016",
    "City__1": "Seoul",
    "Concert Poster": "",
    "Video": "https://www.youtube.com/watch?v=8JbFvGI8Qk8",
    "Note": ""
  },
  {
    "Event_ID": 2,
    "Concert/FM Title": "Like Seventeen \"Shining Diamond\" Concert",
    "Start Date": "July 30, 2016",
    "City": "Seoul",
    "End Date": "August 9, 2016",
    "City__1": "Tokyo",
    "Concert Poster": "",
    "Video": "https://www.youtube.com/watch?v=HuObdIw3FoE",
    "Note": "First concert in Japan"
  },
  {
    "Event_ID": 3,
    "Concert/FM Title": "Seventeen 1st Asia Tour 2016 Shining Diamond",
    "Start Date": "August 13, 2016",
    "City": "Singapore",
    "End Date": "September 11, 2016",
    "City__1": "Taipei",
    "Concert Poster": "",
    "Video": "N/A",
    "Note": ""
  },
  {
    "Event_ID": 4,
    "Concert/FM Title": "1st Caratland",
    "Start Date": "February 10, 2017",
    "City": "Seoul",
    "End Date": "February 12, 2017",
    "City__1": "Seoul",
    "Concert Poster": "",
    "Video": "N/A",
    "Note": ""
  },
  {
    "Event_ID": 5,
    "Concert/FM Title": "17 Japan Concert: Say The Name #Seventeen",
    "Start Date": "February 15, 2017",
    "City": "Kobe",
    "End Date": "February 22, 2017",
    "City__1": "Yokohama",
    "Concert Poster": "",
    "Video": "https://www.youtube.com/watch?v=290s80zZNI0",
    "Note": ""
  },
  {
    "Event_ID": 6,
    "Concert/FM Title": "2017 Seventeen 1st World Tour \"Diamond Edge",
    "Start Date": "July 14, 2017",
    "City": "Seoul",
    "End Date": "October 6, 2017",
    "City__1": "Manila",
    "Concert Poster": "",
    "Video": "https://www.youtube.com/watch?v=0qjTKNZeFkk",
    "Note": "First tour in North America"
  },
  {
    "Event_ID": 7,
    "Concert/FM Title": "2nd Caratland",
    "Start Date": "February 2, 2018",
    "City": "Seoul",
    "End Date": "February 3, 2018",
    "City__1": "Seoul",
    "Concert Poster": "",
    "Video": "N/A",
    "Note": ""
  },
  {
    "Event_ID": 8,
    "Concert/FM Title": "Seventeen 2018 Japan Arena Tour 'SVT'",
    "Start Date": "February 21, 2018",
    "City": "Yokohama",
    "End Date": "March 7, 2018",
    "City__1": "Nagoya",
    "Concert Poster": "",
    "Video": "https://www.youtube.com/watch?v=QqpuUz2TUB0",
    "Note": ""
  },
  {
    "Event_ID": 9,
    "Concert/FM Title": "Seventeen Concert 'Ideal Cut' 2018",
    "Start Date": "June 28, 2018",
    "City": "Seoul",
    "End Date": "November 4, 2018",
    "City__1": "Taipei",
    "Concert Poster": "",
    "Video": "https://www.youtube.com/watch?v=3_0TLD1tKm0",
    "Note": ""
  },
  {
    "Event_ID": 10,
    "Concert/FM Title": "Seventeen Concert 'Ideal Cut' encore",
    "Start Date": "November 3, 2018",
    "City": "Seoul",
    "End Date": "November 3, 2018",
    "City__1": "Seoul",
    "Concert Poster": "",
    "Video": "https://www.youtube.com/watch?v=5kER2MckMpE",
    "Note": ""
  },
  {
    "Event_ID": 11,
    "Concert/FM Title": "3rd Caratland",
    "Start Date": "March 8, 2019",
    "City": "Seoul",
    "End Date": "March 10, 2019",
    "City__1": "Seoul",
    "Concert Poster": "",
    "Video": "N/A",
    "Note": ""
  },
  {
    "Event_ID": 12,
    "Concert/FM Title": "Seventeen 2019 Japan Tour 'Haru'",
    "Start Date": "April 2, 2019",
    "City": "Fukuoka",
    "End Date": "April 27, 2019",
    "City__1": "Osaka",
    "Concert Poster": "",
    "Video": "https://www.youtube.com/watch?v=5MN7EEugTPU",
    "Note": ""
  },
  {
    "Event_ID": 13,
    "Concert/FM Title": "Seventeen World Tour 'Ode to You'",
    "Start Date": "August 30, 2019",
    "City": "Seoul",
    "End Date": "February 8, 2020",
    "City__1": "Manila",
    "Concert Poster": "",
    "Video": "https://www.youtube.com/watch?v=CaNE6xhGvbU",
    "Note": "Taipei, EU canceled due to Covid"
  },
  {
    "Event_ID": 14,
    "Concert/FM Title": "4st Caratland",
    "Start Date": "August 30, 2020",
    "City": "online",
    "End Date": "August 30, 2020",
    "City__1": "online",
    "Concert Poster": "",
    "Video": "https://www.youtube.com/watch?v=RBHggabs_mw&t=28s",
    "Note": ""
  },
  {
    "Event_ID": 15,
    "Concert/FM Title": "2021 SEVENTEEN ONLINE CONCERT 'IN-COMPLETE'",
    "Start Date": "January 23, 2021",
    "City": "online",
    "End Date": "January 23, 2021",
    "City__1": "online",
    "Concert Poster": "",
    "Video": "https://www.youtube.com/watch?v=YEWht-awZrk",
    "Note": ""
  },
  {
    "Event_ID": 16,
    "Concert/FM Title": "5st Caratland",
    "Start Date": "August 8, 2021",
    "City": "online",
    "End Date": "August 8, 2021",
    "City__1": "online",
    "Concert Poster": "",
    "Video": "https://www.youtube.com/watch?v=UOA2jBRff5g",
    "Note": ""
  },
  {
    "Event_ID": 17,
    "Concert/FM Title": "SEVENTEEN CONCERT 'POWER OF LOVE'",
    "Start Date": "November 14, 2021",
    "City": "online",
    "End Date": "November 21, 2021",
    "City__1": "online",
    "Concert Poster": "",
    "Video": "https://www.youtube.com/watch?v=-4QyRflLAQU",
    "Note": ""
  }
]